### ISSUE TITLE
Module compilation failed

### ISSUE THREAD

**Issue by riccardomarin** [rnd-team-dev/plotoptix#15] opened 2020-10-05 23:17 UTC
Hi,

I am facing a new error. I do not know why, but suddenly today even with the simplest example the interpreter returns this error:

```

OPTIX_ERROR_INTERNAL_COMPILER_ERROR: Optix call 'optixModuleCreateFromPTX( m_context, &m_module_compile_options, &m_pipeline_compile_options, ptx.c_str(), ptx.size(), log, &sizeof_log, &mnew )' failed: c:\users\sulej\documents\visual studio 2017\projects\optix\cppsharpoptix7\modules.cpp:23)
Log:
COMPILE ERROR: Module compilation failed
Info: Pipeline parameter "params" size is 280 bytes
Info: Module uses 4 payload values. Pipeline configuration: 4.
Info: Module uses 6 attribute values. Pipeline configuration: 6.
Info: Entry function "__closesthit__occlusion" with semantic type CLOSESTHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 2 basic block(s), 8 instruction(s)
Info: Entry function "__closesthit__occlusion_transparency" with semantic type CLOSESTHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 7 basic block(s), 78 instruction(s)
Info: Entry function "__anyhit__occlusion" with semantic type ANYHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 2 basic block(s), 9 instruction(s)
Info: Entry function "__closesthit__radiance__flat" with semantic type CLOSESTHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 41 basic block(s), 504 instruction(s)
Info: Entry function "__closesthit__radiance__cos" with semantic type CLOSESTHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 41 basic block(s), 528 instruction(s)
Info: Entry function "__closesthit__radiance__blurred_dot" with semantic type CLOSESTHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 46 basic block(s), 563 instruction(s)
Info: Entry function "__closesthit__radiance__diffuse_masked" with semantic type CLOSESTHIT has 1 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 86 basic block(s), 1249 instruction(s)
Info: Entry function "__closesthit__radiance__diffuse" with semantic type CLOSESTHIT has 1 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 81 basic block(s), 1187 instruction(s)
Info: Entry function "__closesthit__radiance__glass" with semantic type CLOSESTHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 124 basic block(s), 1235 instruction(s)
Info: Entry function "__closesthit__radiance__reflective_masked" with semantic type CLOSESTHIT has 2 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 141 basic block(s), 2052 instruction(s)
Info: Entry function "__closesthit__radiance__reflective" with semantic type CLOSESTHIT has 2 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 136 basic block(s), 1998 instruction(s)
Info: Entry function "__closesthit__radiance__light_soft" with semantic type CLOSESTHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 47 basic block(s), 561 instruction(s)
Info: Entry function "__closesthit__radiance__light_hard" with semantic type CLOSESTHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 45 basic block(s), 542 instruction(s)
Info: Entry function "__closesthit__radiance__shadow_catcher" with semantic type CLOSESTHIT has 1 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 77 basic block(s), 1129 instruction(s)
Info: 7 non-entry function(s) have 42 basic block(s), 647 instruction(s)


[ 2][COMPILE FEEDBACK]: COMPILE ERROR: Module compilation failed
Info: Pipeline parameter "params" size is 280 bytes
Info: Module uses 4 payload values. Pipeline configuration: 4.
Info: Module uses 6 attribute values. Pipeline configuration: 6.
Info: Entry function "__closesthit__occlusion" with semantic type CLOSESTHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 2 basic block(s), 8 instruction(s)
Info: Entry function "__closesthit__occlusion_transparency" with semantic type CLOSESTHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 7 basic block(s), 78 instruction(s)
Info: Entry function "__anyhit__occlusion" with semantic type ANYHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 2 basic block(s), 9 instruction(s)
Info: Entry function "__closesthit__radiance__flat" with semantic type CLOSESTHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 41 basic block(s), 504 instruction(s)
Info: Entry function "__closesthit__radiance__cos" with semantic type CLOSESTHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 41 basic block(s), 528 instruction(s)
Info: Entry function "__closesthit__radiance__blurred_dot" with semantic type CLOSESTHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 46 basic block(s), 563 instruction(s)
Info: Entry function "__closesthit__radiance__diffuse_masked" with semantic type CLOSESTHIT has 1 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 86 basic block(s), 1249 instruction(s)
Info: Entry function "__closesthit__radiance__diffuse" with semantic type CLOSESTHIT has 1 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 81 basic block(s), 1187 instruction(s)
Info: Entry function "__closesthit__radiance__glass" with semantic type CLOSESTHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 124 basic block(s), 1235 instruction(s)
Info: Entry function "__closesthit__radiance__reflective_masked" with semantic type CLOSESTHIT has 2 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 141 basic block(s), 2052 instruction(s)
Info: Entry function "__closesthit__radiance__reflective" with semantic type CLOSESTHIT has 2 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 136 basic block(s), 1998 instruction(s)
Info: Entry function "__closesthit__radiance__light_soft" with semantic type CLOSESTHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 47 basic block(s), 561 instruction(s)
Info: Entry function "__closesthit__radiance__light_hard" with semantic type CLOSESTHIT has 0 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 45 basic block(s), 542 instruction(s)
Info: Entry function "__closesthit__radiance__shadow_catcher" with semantic type CLOSESTHIT has 1 trace call(s), 0 continuation callable call(s), 0 direct callable call(s), 77 basic block(s), 1129 instruction(s)
Info: 7 non-entry function(s) have 42 basic block(s), 647 instruction(s)
```

I already tried to delete the cache and re-install the library but it still the same. Any idea on how to solve this?

Thanks again!

**Comment by robertsulej** [comment] 2020-10-06 09:29
That one is a bit mysterious. Did you have any updates of the driver (which version is installed now)?

**Comment by riccardomarin** [comment] 2020-10-06 13:41
RTX 2080 Ti
Driver: 460.20 (27.21.14.6020), 17/09/2020

**Comment by robertsulej** [comment] 2020-10-06 13:54
Ok, thanks. Now I have 460.15. I'll try with the newer one and let you know.

**Comment by robertsulej** [comment] 2020-10-08 13:53
Hi Riccardo,

It seems that the issue is with the 460.20 driver. I have the same error. When I go back to 460.15 everything is OK. I'll file an issue at NVIDIA.

**Comment by robertsulej** [comment] 2020-10-08 15:12
OK, I can confirm that the problem is with the driver. Please, switch back to 460.15 if this is possible for you. For the next release I'll update to OptiX 7.2 that was just released yesterday, maybe this will also remove the driver problem.

**Comment by robertsulej** [comment] 2022-10-07 08:26
Closing, should be solved in the new releases.

**Closed by robertsulej** 2022-10-07 08:26 UTC
